name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest                                      # 在什么环境执行
    steps:                                                      # 步骤
        - name: Checkout                                        # 第一步 Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Update Submodule                                # 第二步 更新子模块
          run: git submodule update --init --recursive

        - name: Setup Hugo                                      # 第三步 Hugo 配置
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: '0.145.0'                           # 使用的 Hugo 版本
              extended: true                                    # 是否使用 extended 版本

        - name: Build Web                                       # 第四步 构建
          run: hugo -E                                          # 构建命令

        - name: Deploy Web                                      # 第四步 发布
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.MYBLOG }}
              EXTERNAL_REPOSITORY: selahRe/selahRe.github.io
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: ./public
              commit_message: auto deploy
